# Generated by Django 3.0.2 on 2020-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('iso_639_2T', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_639_2B', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_639_3', models.CharField(blank=True, max_length=3)),
                ('name_en', models.CharField(max_length=100)),
                ('name_native', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('countries_spoken', models.ManyToManyField(blank=True, to='countries_plus.Country')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name_en'],
            },
        ),
    ]
